CREATE TABLE BANCOS_SANGUE (

    CNPJ VARCHAR2(14) NOT NULL,

    RAZAO_SOCIAL VARCHAR2(255) NOT NULL,

    NOME_FANTASIA VARCHAR2(255) NOT NULL,

    CONSTRAINT BANCOS_SANGUE_PK PRIMARY KEY (CNPJ)

);

 

CREATE TABLE DOADORES (

    CPF VARCHAR2(11) NOT NULL,

    NOME VARCHAR2(255) NOT NULL,

    TIPO_SANGUINEO VARCHAR2(5) NOT NULL,

    TELEFONE VARCHAR2(20),

    ENDERECO VARCHAR2(255),

    CONSTRAINT DOADORES_PK PRIMARY KEY (CPF)

);

 

CREATE TABLE DOACOES (

    CODIGO_DOACAO NUMBER NOT NULL,

    DATA_DOACAO DATE NOT NULL,

    CPF_DOADOR VARCHAR2(11) NOT NULL,

    CNPJ_BANCO_SANGUE VARCHAR2(14) NOT NULL,

    QUANTIDADE_UNIDADES NUMBER NOT NULL,

    CONSTRAINT DOACOES_PK PRIMARY KEY (CODIGO_DOACAO),

    CONSTRAINT DOACOES_DOADOR_FK FOREIGN KEY (CPF_DOADOR) REFERENCES DOADORES (CPF),

    CONSTRAINT DOACOES_FORNECEDOR_FK FOREIGN KEY (CNPJ_BANCO_SANGUE) REFERENCES BANCOS_SANGUE (CNPJ)

);
